### ISSUE TITLE
sh: ./bin/pepito_start.sh: No such file or directory

### ISSUE THREAD

**Issue by edukzs** [LucianoRufo/CT-Flow-Test#2]
![image](https://user-images.githubusercontent.com/54276082/149830282-8a830557-f102-4a5e-a5cb-a51ddbc9bd95.png)

**Comment by LucianoRufo** [comment]
This is a known issue, as the npm packages executes any command correctly except the ones that involve sh files, which are invoked from the route in which you are standing, currently working on it.
